### ISSUE TITLE
usage for iOS libraries

### ISSUE THREAD

**Issue by lucasfernog-crabnebula** [denoland/sui#30]
Can this crate be adapted to work on iOS libraries? I'm trying to iterate over the objects inside an [ar](https://docs.rs/ar/latest/ar/) file (Rust library) and I'd like to inject files into one of them.. they are also Mach-O but do not have the Linkedit segment.. is there any way we could support that?

**Comment by littledivy** [comment]
As such not a goal for this project, it only focuses on targets that Deno supports. I don't really know much about iOS mach-o to help out with an implementation unfortunately.
